apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-varsel-api
  namespace: min-side
  labels:
    team: min-side
spec:
  ingresses:
    - "https://www.nav.no/tms-varsel-api"
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-varsel-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-varsel-api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-varsel-api/metrics
  secureLogs:
    enabled: true
  replicas:
    min: 2
    max: 4
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side-proxy
        - application: decorator-next
          namespace: personbruker
          cluster: prod-gcp
    outbound:
      rules:
        - application: tms-varsel-authority
  resources:
    limits:
      cpu: "1"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 64Mi
  env:
    - name: CORS_ALLOWED_ORIGINS
      value: "*.nav.no"
    - name: VARSEL_AUTHORITY_CLIENT_ID
      value: prod-gcp:min-side:tms-varsel-authority
