name: Bygg branch

on:
  push:
    branches-ignore:
      - master
      - main
      - tms-dependency-admin_*
    paths-ignore:
      - .github/workflows/**
      - README.md
      - howto.md

jobs:
  build-branch:
    runs-on: ubuntu-latest
    steps:

      - name: Sjekk ut koden
        uses: actions/checkout@v4

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/gradle-build-action@v2
        with:
          dependency-graph: generate-and-submit

      - name: Bygg og test prosjekt
        run: ./gradlew build
